[tool.poetry]
name = "morning-digest"
version = "0.1.0"
description = ""
authors = ["David Buckley <buckley.w.davdid@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.4"
beautifulsoup4 = "^4.6"
cchardet = "^2.1"
aiodns = "^1.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
